apiVersion: v1
kind: Namespace
metadata:
  name: kmcp-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kmcp-crds
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/kagent-dev/kmcp/helm/kmcp-crds
  ref:
    tag: "0.2.7"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kmcp-crds
  namespace: kmcp-system
spec:
  interval: 1h
  releaseName: kmcp-crds
  chartRef:
    kind: OCIRepository
    name: kmcp-crds
    namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
