#!/usr/bin/env bash
#MISE description="Deploy: AgentGateway with Helm (KGway)"

set -euo pipefail

helm upgrade -i --create-namespace \
  --namespace agentgateway-system \
  --version v2.2.1 agentgateway-crds oci://ghcr.io/kgateway-dev/charts/agentgateway-crds
helm upgrade -i -n agentgateway-system agentgateway oci://ghcr.io/kgateway-dev/charts/agentgateway \
  --version v2.2.1 \
  -f "$(git rev-parse --show-toplevel)/kubernetes/apps/infra/agentgateway-values.yaml"
