apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: basic-agent-grant
  namespace: default
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: agentgateway-system
  to:
    - group: ""
      kind: Service
