apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ai-backend.yaml
  - gateway.yaml
  - kagent-fix.yaml
  - llm-api-key-secret.yaml
  - llm-secret.yaml
  - model-route.yaml
  - provider-config.yaml
  - reference-grant.yaml
