apiVersion: v1
kind: Secret
metadata:
  name: gemini-api-key
  namespace: kagent
type: Opaque
stringData:
  # This should be replaced with actual key in practice or through `mise` env
  api-key: "$GEMINI_API_KEY"
  Authorization: "$GEMINI_API_KEY"
