#!/usr/bin/env bash
#MISE description="Flux: Bootstrap and system components"
#MISE depends=["setup:infra"]

set -euo pipefail

cd "$(git rev-parse --show-toplevel)/infrastructure/bootstrap"
tofu apply -target=helm_release.flux_operator -target=helm_release.flux_instance -auto-approve
