apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: basic-agent
  namespace: kagent
spec:
  type: Declarative
  declarative:
    systemMessage: |
      You are a helpful assistant running inside a Kubernetes-native agentic infrastructure. 
      Your goal is to assist the user with tasks while utilizing the provided tools and model route.
    modelConfig: basic-agent-config
